name: 'GitHub Actions update package'

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * 1'  #every monday 1:00 am UTC time


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Cache python3
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/Python/3.7.6
          key: ${{ runner.os }}-python
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: install pipenv
        run: pip3 install pipenv
      - name: install package
        run: pipenv update --dev
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: latest
      - name: Test
        run:  pipenv run python setup.py test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          base: master
      - name: notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.